#pragma once

#include <windows.h>

extern HWND hwndMenu;

LRESULT CALLBACK MenuWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK LevelWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK OmokWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK EditProc(HWND, UINT, WPARAM, LPARAM);